.travis.yml, config/build.js, package.json, packages/test/spec/generic/test.spec.js, packages/test/spec/node/test.spec.js
* Remove temporary coverage report
* Corrected lint parameters
* Added release delay in CI
* Get next version from tag name.
=> chore(build): Improve build correctness

config/build.js, package.json
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
```
[ ] Yes
[ ] No
```
=> build: fix release to npm

.travis.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> ci: update travis to new trusty

CONTRIBUTING.md, config/build.js, config/karma.config.js, packages/loki/spec/generic/cloning.spec.js, packages/loki/spec/generic/eventEmitter.spec.js, packages/loki/spec/generic/helpers.spec.js, packages/loki/spec/generic/ops.spec.js, packages/loki/spec/generic/persistence.spec.js, packages/loki/spec/generic/test.spec.js, packages/partitioning-adapter/package.json, packages/partitioning-adapter/spec/generic/partitioning.spec.js, packages/partitioning-adapter/src/partitioning_adapter.js, packages/partitioning-adapter/webpack.config.js
```
[ ] Bugfix
[ x] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(partitioning-adapter): add partitioning-adapter as separate package

config/build.js, packages/loki/webpack.config.js, packages/partitioning-adapter/webpack.config.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> build: export default module for script tag separately

packages/loki/src/loki.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> refactor(loki): get available persistence method from loaded modules

CONTRIBUTING.md, config/build.js, packages/local-storage/package.json, packages/local-storage/spec/web/local_storage.spec.js, packages/local-storage/src/local_storage.js, packages/local-storage/webpack.config.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(local-storage): add local storage as separate package

CONTRIBUTING.md, config/build.js, packages/fs-storage/package.json, packages/fs-storage/spec/node/fs-adapter.spec.js, packages/fs-storage/src/fs_storage.js, packages/fs-storage/webpack.config.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(fs-storage): add fs storage as separate package (#18)

CONTRIBUTING.md, config/build.js, packages/indexed-storage/package.json, packages/indexed-storage/spec/web/indexed_storage.spec.js, packages/indexed-storage/src/indexed_storage.js, packages/indexed-storage/webpack.config.js, packages/loki/src/loki.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(indexed-storage): add indexed storage as separate package

config/build.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> build: add brackets around webpack's var export

packages/loki/src/index.js, packages/loki/src/loki.js, packages/loki/webpack.config.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> refactor(loki): simplify export

packages/fs-storage/spec/node/fs_storage.js, packages/indexed-storage/spec/web/indexed_storage.spec.js, packages/indexed-storage/src/indexed_storage.js, packages/local-storage/spec/web/local_storage.spec.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> Refactor storage tests.

packages/loki/spec/generic/cloning.spec.js, packages/loki/src/clone.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(loki): cloning method for specific classes

packages/loki/spec/generic/sortingIndexing.spec.js, packages/loki/src/collection.js, packages/loki/src/resultset.js, packages/partitioning-adapter/spec/generic/partitioning.spec.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> Change api

.travis.yml, CONTRIBUTING.md, config/build.js, config/eslintrc.js, package-lock.json, package.json, packages/full-text-search/package.json, packages/full-text-search/spec/generic/inverted_index.spec.js, packages/full-text-search/spec/generic/languages/de.js, packages/full-text-search/spec/generic/languages/language.spec.js, packages/full-text-search/spec/generic/query_builder.spec.js, packages/full-text-search/spec/generic/search/fuzzy.spec.js, packages/full-text-search/spec/generic/search/wildcard.spec.js, packages/full-text-search/spec/generic/tokenizer.spec.js, packages/full-text-search/spec/node/MOCK_DATA.js, packages/full-text-search/spec/node/QUERIES.js, packages/full-text-search/spec/node/elasticsearch.spec.js, packages/full-text-search/src/full_text_search.js, packages/full-text-search/src/index.js, packages/full-text-search/src/index_searcher.js, packages/full-text-search/src/inverted_index.js, packages/full-text-search/src/language/de.js, packages/full-text-search/src/language/support.js, packages/full-text-search/src/queries.js, packages/full-text-search/src/scorer.js, packages/full-text-search/src/tokenizer.js, packages/full-text-search/src/utils.js, packages/full-text-search/webpack.config.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> Add full text search.

packages/common/plugin.ts, packages/common/types.ts, packages/fs-storage/spec/node/fs_storage.spec.ts, packages/fs-storage/src/fs_storage.ts, packages/full-text-search/spec/generic/full_text_search.spec.ts, packages/full-text-search/spec/node/elasticsearch.spec.ts, packages/full-text-search/src/full_text_search.ts, packages/full-text-search/src/index_searcher.ts, packages/full-text-search/src/inverted_index.ts, packages/full-text-search/src/scorer.ts, packages/indexed-storage/spec/web/indexed_storage.spec.ts, packages/indexed-storage/src/indexed_storage.ts, packages/local-storage/spec/web/local_storage.spec.ts, packages/local-storage/src/local_storage.ts, packages/loki/spec/generic/joins.spec.ts, packages/loki/spec/generic/persistence.spec.ts, packages/loki/src/collection.ts, packages/loki/src/dynamic_view.ts, packages/loki/src/loki.ts, packages/loki/src/memory_adapter.ts, packages/loki/src/resultset.ts, packages/partitioning-adapter/src/partitioning_adapter.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> Integrate fts to loki

docs/index.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs: fix API reference link

packages/full-text-search/spec/generic/search/fuzzy.spec.ts, packages/full-text-search/src/index_searcher.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(full-text-search): fix fuzzy extended to withdraw wrong results

packages/indexed-storage/src/indexed_storage.ts, packages/loki/src/collection.ts, packages/loki/src/resultset.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> refactor(loki): remove 'typeof x === "undefined"' to check for undefined

README.md, packages/full-text-search-language-de/package.json, packages/full-text-search-language-en/package.json, packages/full-text-search-language/package.json, packages/full-text-search-language/spec/helper/create_lanuage_test.ts, packages/full-text-search/package.json, packages/full-text-search/spec/generic/full_text_search.spec.ts, packages/full-text-search/src/full_text_search.ts, packages/loki/src/resultset.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> Small refactor

packages/full-text-search-language/spec/helper/create_lanuage_test.ts, packages/full-text-search/spec/generic/search/fuzzy.spec.ts, packages/full-text-search/spec/generic/search/wildcard.spec.ts, packages/full-text-search/spec/node/elasticsearch.spec.ts, packages/full-text-search/src/full_text_search.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> refactor(full-text-search): make the id field optional undefined

CONTRIBUTING.md, README.md, config/build.js, packages/full-text-search/spec/generic/full_text_search.spec.ts, packages/loki/spec/generic/dynamic_view.spec.ts, packages/loki/spec/generic/persistence.spec.ts, packages/loki/spec/generic/unique.spec.ts, packages/loki/src/memory_storage.ts, packages/memory-storage/package.json, packages/memory-storage/spec/generic/memory_storage.spec.ts, packages/memory-storage/src/index.ts, packages/memory-storage/src/memory_storage.ts, packages/memory-storage/webpack.config.js, packages/partitioning-adapter/spec/generic/partitioning.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> Memory adapter

packages/full-text-search-language/src/index.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(full-text-search-language): add missing function export

packages/full-text-search/spec/generic/full_text_search.spec.ts, packages/full-text-search/spec/node/elasticsearch.spec.ts, packages/full-text-search/src/full_text_search.ts, packages/full-text-search/src/index_searcher.ts, packages/full-text-search/src/query_builder.ts, packages/full-text-search/src/scorer.ts, packages/loki/src/dynamic_view.ts, packages/loki/src/result_set.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(full-text-search): add an optional score explanation

packages/loki/spec/generic/binaryidx.spec.ts, packages/loki/spec/generic/dynamic_view.spec.ts, packages/loki/spec/generic/remove.spec.ts, packages/loki/spec/generic/test.spec.ts, packages/loki/spec/generic/unique.spec.ts, packages/loki/src/collection.ts, packages/loki/src/dynamic_view.ts, packages/loki/src/loki.ts, packages/loki/src/result_set.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(loki): improve generic typings

packages/full-text-search-language/spec/helper/create_lanuage_test.ts, packages/full-text-search/spec/generic/full_text_search.spec.ts, packages/full-text-search/spec/generic/search/fuzzy.spec.ts, packages/full-text-search/spec/generic/search/wildcard.spec.ts, packages/full-text-search/spec/node/elasticsearch.spec.ts, packages/full-text-search/src/full_text_search.ts, packages/loki/src/collection.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(full-text-search): rename field option "name" to "field"

packages/full-text-search/spec/generic/search/fuzzy.spec.ts, packages/full-text-search/spec/node/MOCK_DATA.ts, packages/full-text-search/spec/node/QUERIES.ts, packages/full-text-search/spec/node/elasticsearch.spec.ts, packages/full-text-search/src/index_searcher.ts, packages/full-text-search/src/scorer.ts
…ation for fuzzy query
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(full-text-search) fix fuzzy's prefix length, edit distance and idf

README.md
Self explanatory
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
Confusing
Not confusing
```
[ ] Yes
[x] No
```
None.
=> Fixed @loki => @lokijs

packages/full-text-search/spec/node/QUERIES.ts, packages/full-text-search/src/index_searcher.ts, packages/full-text-search/src/query_types.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(full-text-search): remove unnecessary array query

packages/loki/spec/generic/dynamic_view.spec.ts, packages/loki/spec/generic/persistence.spec.ts, packages/loki/src/loki.ts
See techfort/LokiJS@59aa3af10043f8548a300975947cc402ca44c74f
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(loki): fix a autosave race condition when using asynchronous adapter

packages/common/types.ts, packages/full-text-search/spec/generic/full_text_search.spec.ts, packages/full-text-search/src/full_text_search.ts, packages/loki/spec/generic/binaryidx.spec.ts, packages/loki/spec/generic/collection.spec.ts, packages/loki/spec/generic/persistence.spec.ts, packages/loki/spec/generic/sortingIndexing.spec.ts, packages/loki/spec/generic/stats.spec.ts, packages/loki/spec/generic/test.spec.ts, packages/loki/spec/generic/transforms.spec.ts, packages/loki/spec/generic/typed.spec.ts, packages/loki/src/collection.ts, packages/loki/src/dynamic_view.ts, packages/loki/src/loki.ts, packages/loki/src/result_set.ts, packages/loki/src/unique_index.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> Change nested properties

packages/loki/spec/generic/binaryidx.spec.ts, packages/loki/src/collection.ts
Since validating indices might take a while if the collection contains many documents, random sampling allows sampling random points within a binary index to verify it is sequenced properly with its next neighbor.
See techfort/LokiJS@1c2aa85a821ef38b1d38f61f498c34d84930e7df
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(loki): add diagnostic function to test binary index validity

LICENSE, README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs: update license

config/build.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> build: add readme to npm packages

README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs: link to correct npm packages in readme

package.json, packages/full-text-search/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs: update licenses in package.json

package.json, packages/full-text-search/spec/node/elasticsearch.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #96 
```
[ ] Yes
[x] No
```
=> feat(fts): if elasticsearch is not available, disable relevant unit tests

config/build.js, package-lock.json, package.json
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
Issue Number: #96 
```
[ ] Yes
[x] No
```
=> build: make cross platform compatible

packages/full-text-search/src/index.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(fts): add analyse to exported function

.babelrc
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> build: remove babelrc

config/karma.config.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> test: use headless chrome for karma

.travis.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> build: use headless chrome in travis

packages/loki/spec/generic/persistence.spec.ts, packages/loki/src/loki.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> Fix autosave and autoload

.travis.yml, package-lock.json, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> build: use codecov for coverage reports

README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> doc: add codecov badge to readme

packages/full-text-search/spec/generic/full_text_search.spec.ts, packages/full-text-search/src/full_text_search.ts, packages/full-text-search/src/index_searcher.ts, packages/full-text-search/src/inverted_index.ts, packages/full-text-search/src/scorer.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(fts): allow number and strings as document id

config/webpack-config-creator.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> build: define module name for AMD output

README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs: remove html code from readme

config/build.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> build: fix git add for packages

packages/full-text-search/spec/node/QUERIES.ts, packages/full-text-search/src/index_searcher.ts, packages/full-text-search/src/scorer.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(fts): apply bool query boost to sub query results

packages/full-text-search/spec/node/QUERIES.ts, packages/full-text-search/spec/node/elasticsearch.spec.ts, packages/full-text-search/src/index_searcher.ts, packages/full-text-search/src/scorer.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(full-text-search): handle not and filter bool queries right

packages/full-text-search/spec/node/QUERIES.ts, packages/full-text-search/spec/node/elasticsearch.spec.ts, packages/full-text-search/src/index_searcher.ts, packages/full-text-search/src/query_types.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(full-text-search): implement conditional minimum should match parameters

scripts/deploy.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> build: fix name of release branch

CHANGELOG.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs: fix package names inside changelog

.travis.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> build: update travis configuration

.gitignore, .travis.yml, scripts/build.ts, scripts/deploy.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> build: separate build targets for developing and deploying

packages/loki/spec/generic/btreeidx.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> test(loki): add nested property test for the BST

packages/loki/spec/generic/btreeidx.spec.ts, packages/loki/src/collection.ts, packages/loki/src/dynamic_view.ts, packages/loki/src/helper.ts, packages/loki/src/result_set.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> refactor(loki): simplify generic classes

packages/loki/spec/generic/test.spec.ts, packages/loki/src/collection.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(loki): fix transaction rollback with nested properties

benchmark/benchmark.js, benchmark/benchmark_indexes.js, package-lock.json, packages/loki/spec/generic/cloning.spec.ts, packages/loki/spec/generic/collection.spec.ts, packages/loki/spec/generic/unique.spec.ts, packages/loki/src/collection.ts, packages/loki/src/result_set.ts, packages/loki/src/unique_index.ts
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
Issue Number: #95 
Currently unique indexes are slower than they should be using collection.by()
Currently loki index is using slower binary search within collection.get()
Unique indexes have two way map internally and return $loki from get(value)
collection.by() now bypasses slower resultset.find() codepath, yielding faster results
A new collection._lokimap property has been added to allow loki->doc lookups to be faster
collection.get() …
=> refactor(loki): unique and loki map optimizations #95

benchmark/benchmark.js, benchmark/benchmark_indexes.js, packages/loki/spec/generic/avl-index.spec.ts, packages/loki/spec/generic/ops.spec.ts, packages/loki/spec/generic/persistence.spec.ts, packages/loki/spec/generic/test.spec.ts, packages/loki/src/avl_index.ts, packages/loki/src/collection.ts, packages/loki/src/helper.ts
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
```
[ ] Yes
[ ] No
```
=> refactor(loki): rename BinaryTreeIndex to AvlTreeIndex

scripts/build.ts, scripts/common.ts, scripts/deploy.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> build: allow offline builds

packages/loki/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> build: add missing 'types' property in Loki's package.json

.travis.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> update CI to work with current versions

packages/loki/spec/generic/unique.spec.ts, packages/loki/src/result_set.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(loki): unique search with no matching entry should not fail

packages/full-text-search/spec/generic/inverted_index.spec.ts, packages/full-text-search/spec/node/MOCK_DATA.ts, packages/full-text-search/spec/node/QUERIES.ts, packages/full-text-search/src/full_text_search.ts, packages/full-text-search/src/inverted_index.ts
=> feat(fts): support optional, empty or number fields
